default:
  image: python:3.11

stages:
  - install
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - ~/.cache/pip

install-job:
  stage: install
  script:
    - pip install -r requirements.txt

test-job:
  stage: test
  script:
    - pip install coverage
    - coverage run -m unittest
    - coverage combine
    - coverage report
  dependencies:
    - install-job
  artifacts:
    paths:
      - coverage_html/

deploy-job:
  stage: deploy
  script:
    - echo "Pipeline finished!"
  only:
    - main
