stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - ~/.cache/pip

test-job:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pip install --upgrade pip
    - coverage run -m unittest
    - coverage report
    - coverage html
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.html

deploy-job:
  stage: deploy
  script:
    - echo "Pipeline finished!"
  only:
    - main
