stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - ~/.cache/pip

# Python unit tests
unit test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pip install --upgrade pip
    - coverage run -m unittest
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# Bash Linting
shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  before_script:
    - shellcheck --version
  script:
    - shellcheck scripts/*.sh

# Bash Formatting
shfmt:
  image: mvdan/shfmt:v3.2.0-alpine
  stage: test
  before_script:
    - shfmt -version
  script:
    - shfmt -i 2 -ci -d scripts/

deploy-job:
  stage: deploy
  script:
    - echo "Pipeline finished!"
  only:
    - main
