default:
  image: python:3.12

stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - ~/.cache/pip

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - coverage run -m unittest
    - coverage report
    - coverage xml
  artifacts:
    paths:
      - coverage/

deploy-job:
  stage: deploy
  script:
    - echo "Pipeline finished!"
  only:
    - main
