default:
  image: python:3.11
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt


build-job:
  stage: build
  script:
    - echo "Beginning of the pipeline."

test-job:
  stage: test
  script:
    - coverage run -m unittest
    - coverage report

deploy-job:
  stage: deploy
  script:
    - echo "Pipeline finished!"
