apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cats-classifier-backend:001
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
        ports:
        - containerPort: 8000
        env:
        - name: TF_SERVING_HOST
          value: tf-cats-classifier.default.svc.cluster.local:8500
