---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eu.gcr.io/GCP_PROJECT_NAME/my_image_name:001
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8000
        env:
        - name: TF_SERVING_HOST
          value: model.default.svc.cluster.local:8500
