apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-cats-classifier
spec:
  selector:
    matchLabels:
      app: tf-serving-cats-classifier
  template:
    metadata:
      labels:
        app: tf-serving-cats-classifier
    spec:
      containers:
      - name: tf-serving-cats-classifier
        image: cats-classifier-model:resnet50-v1-001
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
        - containerPort: 8500
